### ISSUE TITLE
PROBLEMAS

### ISSUE THREAD

**Issue by antoniosilvat** [kowalski93/Green-View-Index-for-QGIS#2]
Mensaje de error:
Traceback (most recent call last):
File "C:\Users/asilv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\green_view_index\greenviewindex\generate_sample_points_algorithm.py", line 331, in processAlgorithm
(sink, dest_id) = self.parameterAsSink(
TypeError: QgsProcessingAlgorithm.parameterAsSink(): argument 5 has unexpected type 'int'

**Comment by kowalski93** [comment]
>

**Comment by kowalski93** [comment]
Please share more info, such as your QGIS version, what you tried to do exactly, and ideally your dataset as well

**Comment by antoniosilvat** [comment]
No se pudo cargar el complemento 'green_view_index' debido a un error al llamar a su método classFactory() 

ModuleNotFoundError: No module named 'skimage' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/asilv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\green_view_index\__init__.py", line 41, in classFactory
    from .green_view_index import GreenViewIndexPlugin
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/asilv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\green_view_index\green_view_index.py", line 43, in 
    from .green_view_index_provider import GreenViewIndexProvider
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/asilv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\green_view_index\green_view_index_provider.py", line 37, in 
    from .greenviewindex.calculate_green_view_index_algorithm import CalculateGreenViewIndex
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/asilv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\green_view_index\greenviewindex\calculate_green_view_index_algorithm.py", line 54, in 
    from skimage.io import imread,imsave
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'skimage'


Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.32.3-Lima Lima, 67d46100b5

**Comment by kowalski93** [comment]
Please check the [part](https://github.com/kowalski93/Green-View-Index-for-QGIS#installation---requirements) of the Readme page about installing dependencies. You must install libraries skimage and gpsphoto for the plugin to run.

**Comment by antoniosilvat** [comment]
The two libraries were installed in accordance with what the guide indicates.
But this appears to me:

Versión de QGIS: 3.32.3-Lima
Revisión del código de QGIS: 67d46100b5
Versión de Qt: 5.15.3
Python version: 3.9.5
Versión de GDAL: 3.7.2
Versión de GEOS: 3.12.0-CAPI-1.18.0
Versión de PROJ: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.5 (git-version: 24f78d)
El algoritmo comenzó en: 2024-01-10T02:26:52
Algoritmo 'Generate Sample Points' comenzando…
Parámetros de entrada:
{ 'GEOMETRY INPUT TYPE' : 1, 'INPUT AOI' : None, 'INPUT ROAD NETWORK' : 'C:/Users/asilv/OneDrive/IMPLAN/2019 SIG IMPLAN/IMPLAN/Homologación Colonias Urbanas 2021/20210615 Capas/Vialidades Cabecera.shp|layername=Vialidades Cabecera', 'MINIMUM DISTANCE' : 0, 'NUMBER OF POINTS' : 100, 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "C:\Users/asilv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\green_view_index\greenviewindex\generate_sample_points_algorithm.py", line 331, in processAlgorithm
(sink, dest_id) = self.parameterAsSink(
TypeError: QgsProcessingAlgorithm.parameterAsSink(): argument 5 has unexpected type 'int'

Execution failed after 0.15 segundos

Cargando las capas resultantes
Algoritmo 'Generate Sample Points' finalizado

**Comment by kowalski93** [comment]
Please use a **long term release** of QGIS. Not the latest experimental one. 
![image](https://github.com/kowalski93/Green-View-Index-for-QGIS/assets/39091833/2c08d029-1d00-4756-b2cf-57ef99522964)
